In [151]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [152]:
import sklearn
print(sklearn.__version__)
print(sklearn.__file__)

1.7.2
C:\Users\acer\anaconda3\Lib\site-packages\sklearn\__init__.py

In [153]:
df=pd.read_csv('m1.csv')
df2=pd.read_csv('m2.csv')

In [154]:
df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [155]:
df2.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [156]:
df=df.merge(df2,on='title')

In [157]:
df.head(1)

,movie_id,title,cast,crew,budget,genres,homepage,id,keywords,original_language,...,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,vote_average,vote_count
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,...,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,7.2,11800

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   movie_id              4809 non-null   int64
 1   title                 4809 non-null   object
 2   cast                  4809 non-null   object
 3   crew                  4809 non-null   object
 4   budget                4809 non-null   int64
 5   genres                4809 non-null   object
 6   homepage              1713 non-null   object
 7   id                    4809 non-null   int64
 8   keywords              4809 non-null   object
 9   original_language     4809 non-null   object
 10  original_title        4809 non-null   object
 11  overview              4806 non-null   object
 12  popularity            4809 non-null   float64
 13  production_companies  4809 non-null   object
 14  production_countries  4809 non-null   object
 15  release_date          4808 non-null   object
 16  revenue               4809 non-null   int64
 17  runtime               4807 non-null   float64
 18  spoken_languages      4809 non-null   object
 19  status                4809 non-null   object
 20  tagline               3965 non-null   object
 21  vote_average          4809 non-null   float64
 22  vote_count            4809 non-null   int64
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [159]:
df=df[['movie_id','genres','title','overview','keywords','cast','crew']]

In [160]:
df.isnull().sum()

movie_id    0
genres      0
title       0
overview    3
keywords    0
cast        0
crew        0
dtype: int64

In [161]:
df.dropna(inplace=True)

In [162]:
df.duplicated().sum()

np.int64(0)

In [163]:
genres=df.iloc[0].genres
keyword=df.iloc[3].keywords
crew=df.iloc[5].crew
cast=df.iloc[4].cast

In [164]:
import ast 
def extraction( genres):
    return[i['name']for i in 
           ast.literal_eval(genres)]

In [165]:
type(df)

pandas.core.frame.DataFrame

In [166]:
df['genres']=df['genres'].apply(extraction)

In [167]:
df['keywords']=df['keywords'].apply(extraction)

In [168]:
import ast
def extraction2(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']== 'Director':
                l.append(i['name'])
    return l

In [169]:
df['crew']=df['crew'].apply(extraction2)

In [170]:
df['crew'][0]

['James Cameron']

In [171]:
import ast 
def extraction3( genres):
    return[i['name']for i in 
           ast.literal_eval(genres)
           if 'job'=='director']

In [172]:
df.sample

<bound method NDFrame.sample of       movie_id                                         genres  \
0        19995  [Action, Adventure, Fantasy, Science Fiction]
1          285                   [Adventure, Fantasy, Action]
2       206647                     [Action, Adventure, Crime]
3        49026               [Action, Crime, Drama, Thriller]
4        49529           [Action, Adventure, Science Fiction]
...        ...                                            ...
4804      9367                      [Action, Crime, Thriller]
4805     72766                              [Comedy, Romance]
4806    231617             [Comedy, Drama, Romance, TV Movie]
4807    126186                                             []
4808     25975                                  [Documentary]

                                         title  \
0                                       Avatar
1     Pirates of the Caribbean: At World's End
2                                      Spectre
3                        The Dark Knight Rises
4                                  John Carter
...                                        ...
4804                               El Mariachi
4805                                 Newlyweds
4806                 Signed, Sealed, Delivered
4807                          Shanghai Calling
4808                         My Date with Drew

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...
1     Captain Barbossa, long believed to be dead, ha...
2     A cryptic message from Bond’s past sends him o...
3     Following the death of District Attorney Harve...
4     John Carter is a war-weary, former military ca...
...                                                 ...
4804  El Mariachi just wants to play his guitar and ...
4805  A newlywed couple's honeymoon is upended by th...
4806  "Signed, Sealed, Delivered" introduces a dedic...
4807  When ambitious New York attorney Sam is sent t...
4808  Ever since the second grade when he first saw ...

                                               keywords  \
0     [culture clash, future, space war, space colon...
1     [ocean, drug abuse, exotic island, east india ...
2     [spy, based on novel, secret agent, sequel, mi...
3     [dc comics, crime fighter, terrorist, secret i...
4     [based on novel, mars, medallion, space travel...
...                                                 ...
4804  [united states–mexico barrier, legs, arms, pap...
4805                                                 []
4806  [date, love at first sight, narration, investi...
4807                                                 []
4808          [obsession, camcorder, crush, dream girl]

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...
1     [{"cast_id": 4, "character": "Captain Jack Spa...
2     [{"cast_id": 1, "character": "James Bond", "cr...
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4     [{"cast_id": 5, "character": "John Carter", "c...
...                                                 ...
4804  [{"cast_id": 1, "character": "El Mariachi", "c...
4805  [{"cast_id": 1, "character": "Buzzy", "credit_...
4806  [{"cast_id": 8, "character": "Oliver O\u2019To...
4807  [{"cast_id": 3, "character": "Sam", "credit_id...
4808  [{"cast_id": 3, "character": "Herself", "credi...

                                          crew
0                              [James Cameron]
1                             [Gore Verbinski]
2                                 [Sam Mendes]
3                          [Christopher Nolan]
4                             [Andrew Stanton]
...                                        ...
4804                        [Robert Rodriguez]
4805                            [Edward Burns]
4806                             [Scott Smith]
4807                             [Daniel Hsia]
4808  [Brian Herzlinger, Jon Gunn, Brett Winn]

[4806 rows x 7 columns]>

In [173]:
df['overview']=df['overview'].apply(lambda x:x.split())

In [174]:
df

,movie_id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...",[James Cameron]
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,9367,"[Action, Crime, Thriller]",El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[united states–mexico barrier, legs, arms, pap...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...",[Robert Rodriguez]
4805,72766,"[Comedy, Romance]",Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...",[Edward Burns]
4806,231617,"[Comedy, Drama, Romance, TV Movie]","Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[date, love at first sight, narration, investi...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...",[Scott Smith]
4807,126186,[],Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...",[Daniel Hsia]
4808,25975,[Documentary],My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[obsession, camcorder, crush, dream girl]","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [175]:
import ast 
def extractioncast( genres):
    return[i['name']for i in 
           ast.literal_eval(genres)[:3]]

In [176]:
import ast

def extractioncast(genres):
    if genres is None:
        return []
    return [i['name'] for i in ast.literal_eval(genres)[:3]]

In [177]:
print(df['cast'].isnull().sum())     # how many None/NaN rows exist
print(df[df['cast'].isnull()])   # inspect them

0
Empty DataFrame
Columns: [movie_id, genres, title, overview, keywords, cast, crew]
Index: []

In [178]:
import ast
import pandas as pd

def extractioncast(genres):
    if pd.isna(genres) or genres is None:
        return []
    try:
        return [i['name'] for i in ast.literal_eval(genres)[:3]]
    except (ValueError, SyntaxError):
        return []

In [179]:
df['cast'] =df['cast'].apply(extractioncast)

In [180]:
df

,movie_id,genres,title,overview,keywords,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]
...,...,...,...,...,...,...,...
4804,9367,"[Action, Crime, Thriller]",El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui...","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez]
4805,72766,"[Comedy, Romance]",Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended...",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns]
4806,231617,"[Comedy, Drama, Romance, TV Movie]","Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,...","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith]
4807,126186,[],Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is...",[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia]
4808,25975,[Documentary],My Date with Drew,"[Ever, since, the, second, grade, when, he, fi...","[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]"

In [181]:

df['title']=df['title'].apply(lambda x:[x])

In [182]:
df['tags']=df['genres']+df['cast']+df['crew']+df['keywords']+df['title']+df['overview']

In [183]:
df

,movie_id,genres,title,overview,keywords,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, Science Fiction]",[Avatar],"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[Action, Adventure, Fantasy, Science Fiction, ..."
1,285,"[Adventure, Fantasy, Action]",[Pirates of the Caribbean: At World's End],"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Adventure, Fantasy, Action, Johnny Depp, Orla..."
2,206647,"[Action, Adventure, Crime]",[Spectre],"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[Action, Adventure, Crime, Daniel Craig, Chris..."
3,49026,"[Action, Crime, Drama, Thriller]",[The Dark Knight Rises],"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Action, Crime, Drama, Thriller, Christian Bal..."
4,49529,"[Action, Adventure, Science Fiction]",[John Carter],"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[Action, Adventure, Science Fiction, Taylor Ki..."
...,...,...,...,...,...,...,...,...
4804,9367,"[Action, Crime, Thriller]",[El Mariachi],"[El, Mariachi, just, wants, to, play, his, gui...","[united states–mexico barrier, legs, arms, pap...","[Carlos Gallardo, Jaime de Hoyos, Peter Marqua...",[Robert Rodriguez],"[Action, Crime, Thriller, Carlos Gallardo, Jai..."
4805,72766,"[Comedy, Romance]",[Newlyweds],"[A, newlywed, couple's, honeymoon, is, upended...",[],"[Edward Burns, Kerry Bishé, Marsha Dietlein]",[Edward Burns],"[Comedy, Romance, Edward Burns, Kerry Bishé, M..."
4806,231617,"[Comedy, Drama, Romance, TV Movie]","[Signed, Sealed, Delivered]","[""Signed,, Sealed,, Delivered"", introduces, a,...","[date, love at first sight, narration, investi...","[Eric Mabius, Kristin Booth, Crystal Lowe]",[Scott Smith],"[Comedy, Drama, Romance, TV Movie, Eric Mabius..."
4807,126186,[],[Shanghai Calling],"[When, ambitious, New, York, attorney, Sam, is...",[],"[Daniel Henney, Eliza Coupe, Bill Paxton]",[Daniel Hsia],"[Daniel Henney, Eliza Coupe, Bill Paxton, Dani..."
4808,25975,[Documentary],[My Date with Drew],"[Ever, since, the, second, grade, when, he, fi...","[obsession, camcorder, crush, dream girl]","[Drew Barrymore, Brian Herzlinger, Corey Feldman]","[Brian Herzlinger, Jon Gunn, Brett Winn]","[Documentary, Drew Barrymore, Brian Herzlinger..."

In [184]:
new_df=df[['movie_id','title','tags']]

In [185]:
new_df.tags

0       [Action, Adventure, Fantasy, Science Fiction, ...
1       [Adventure, Fantasy, Action, Johnny Depp, Orla...
2       [Action, Adventure, Crime, Daniel Craig, Chris...
3       [Action, Crime, Drama, Thriller, Christian Bal...
4       [Action, Adventure, Science Fiction, Taylor Ki...
                              ...
4804    [Action, Crime, Thriller, Carlos Gallardo, Jai...
4805    [Comedy, Romance, Edward Burns, Kerry Bishé, M...
4806    [Comedy, Drama, Romance, TV Movie, Eric Mabius...
4807    [Daniel Henney, Eliza Coupe, Bill Paxton, Dani...
4808    [Documentary, Drew Barrymore, Brian Herzlinger...
Name: tags, Length: 4806, dtype: object

In [186]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\acer\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\acer\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\acer\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\acer\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\users\acer\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\acer\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [187]:
#new_df['tags']=new_df['tags'].str.split().str[0]

In [188]:
new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\acer\AppData\Local\Temp\ipykernel_19744\3239638080.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']= new_df['tags'].apply(lambda x:" ".join(x))

In [189]:
new_df.head()

,movie_id,title,tags
0,19995,[Avatar],Action Adventure Fantasy Science Fiction Sam W...
1,285,[Pirates of the Caribbean: At World's End],Adventure Fantasy Action Johnny Depp Orlando B...
2,206647,[Spectre],Action Adventure Crime Daniel Craig Christoph ...
3,49026,[The Dark Knight Rises],Action Crime Drama Thriller Christian Bale Mic...
4,49529,[John Carter],Action Adventure Science Fiction Taylor Kitsch...

In [190]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [191]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [192]:
print(new_df[['title','tags']].head(10))

                                        title  \
0                                    [Avatar]
1  [Pirates of the Caribbean: At World's End]
2                                   [Spectre]
3                     [The Dark Knight Rises]
4                               [John Carter]
5                              [Spider-Man 3]
6                                   [Tangled]
7                   [Avengers: Age of Ultron]
8    [Harry Potter and the Half-Blood Prince]
9        [Batman v Superman: Dawn of Justice]

                                                tags
0  Action Adventure Fantasy Science Fiction Sam W...
1  Adventure Fantasy Action Johnny Depp Orlando B...
2  Action Adventure Crime Daniel Craig Christoph ...
3  Action Crime Drama Thriller Christian Bale Mic...
4  Action Adventure Science Fiction Taylor Kitsch...
5  Fantasy Action Adventure Tobey Maguire Kirsten...
6  Animation Family Zachary Levi Mandy Moore Donn...
7  Action Adventure Science Fiction Robert Downey...
8  Adventure Fantasy Family Daniel Radcliffe Rupe...
9  Action Adventure Fantasy Ben Affleck Henry Cav...

In [193]:
vectors
print(vectors[0].sum())         
print((vectors[0] > 0).sum())   
print(new_df['tags'].isna().sum())          # any NaNs?
print(new_df['tags'].apply(len).describe())  # are most rows very short/empty?
print(new_df['tags'].duplicated().sum())     # are many rows identical?

54
47
0
count    4806.000000
mean      482.517270
std       179.866734
min        43.000000
25%       346.000000
50%       466.000000
75%       584.000000
max      1596.000000
Name: tags, dtype: float64
0

In [194]:
from nltk.stem.porter import PorterStemmer

In [195]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'],
      shape=(5000,), dtype=object)

In [196]:
ps=PorterStemmer()

In [197]:
def stem(text):
    y=[]
    for i in text.split():
        y.append (ps.stem(i))
    return " ".join(y)

In [198]:
type(new_df['tags'][0])

str

In [199]:
stem("'Action Adventure Fantasy Science Fiction Sam Worthington Zoe Saldana Sigourney Weaver James Cameron culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Avatar In the 22+nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'")

"'action adventur fantasi scienc fiction sam worthington zoe saldana sigourney weaver jame cameron cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d avatar in the 22+nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization.'"

In [200]:
new_df['tags']=new_df['tags'].apply(stem)

C:\Users\acer\AppData\Local\Temp\ipykernel_19744\3514595201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)

In [201]:
print(new_df['tags'].duplicated().sum())   # should now be much lower
print(new_df['tags'].value_counts().head(5))
print(similarity[0][:10])   # should show varied decimal values, not just 0/1

0
tags
action adventur fantasi scienc fiction sam worthington zoe saldana sigourney weaver jame cameron cultur clash futur space war space coloni societi space travel futurist romanc space alien tribe alien planet cgi marin soldier battl love affair anti war power relat mind and soul 3d avatar in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
action adventur anim fantasi scienc fiction tom kane corey burton mat luca genndi tartakovski war space opera clone trooper star wars: clone wars: volum 1 the saga continu with the emmy-win "star wars: clone wars." thi anim micro-series, direct by genndi tartakovsky, captur georg lucas' vision in a dynam anim style that is a visual delight for all ages. "star wars: clone wars" volum 1 reveal the epic adventur that bridg the stori arc between "star wars: episod ii: attack of the clones" and "star wars: episod iii: reveng of the sith." follow the valiant jedi knight and the brave soldier of the republic' clone armi as they battl against the droid forc of the separatists, led by the evil sith lord, count dooku. wit the battl that made galact hero out of anakin skywalk and obi-wan kenobi, and along the way get a first look at the new menac from episod iii, gener grevious. thi is a must-hav for ani "star wars" collection.    1
drama karin viard joeystarr marina foï maïwenn woman director poliss the daili grind for the cop of the polic department' juvenil protect unit - take in child molesters, bust underag pickpockets, interrog abus parents, confront the excess of teen sexuality, enjoy solidar with colleagu and laugh uncontrol at the most unthink moments. know the worst exist and live with it. how do these cop balanc their privat live and the realiti they confront everi work day? fred, the group' hypersensit wild card, is go to have a hard time face the scrutini of melissa, a photograph on a ministri of the interior assign to document the unit.                                                                                                                                                                                                                                                                                                                 1
drama histori war brendan cowel harrison gilbertson steve le marquand jeremi sim beneath hill 60 the true stori of australia' cat-and-mous underground mine warfar – one of the most misunderstood, misrepres and mystifi conflict of ww i. it wa a secret struggl beneath the western front that combin dare engineering, technolog and science, and few on the surfac knew of the brave, claustrophob and sometim barbar work of these tunnellers.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
thriller mysteri scienc fiction ryan phillipp sarah polley piper perabo roland suso richter infidel amnesia paranoia nightmar time puzzl murder suspens memori hospit doctor fear guilt discoveri loop the i insid simon cabl wake up in a hospit bed, confus and disoriented. he soon discov from doctor that he ha amnesia and is unabl to rememb the last two year of hi life. cabl investig what ha happen to him and slowli piec togeth hi enigmat past.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Name: count, dtype: int64
[1.         0.06302535 0.06554735 0.04206101 0.27101851 0.13157895
 0.03476173 0.11561466 0.03311331 0.09462916]

In [202]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'],
      shape=(5000,), dtype=object)

In [203]:
from sklearn.metrics.pairwise import cosine_similarity


vectors = cv.fit_transform(new_df['tags']).toarray()

similarity = cosine_similarity(vectors)

print(similarity.shape)     # (num_movies, num_movies)
print(similarity[0])        # similarity of movie 0 with all others

(4806, 4806)
[1.         0.06302535 0.06554735 ... 0.04370374 0.02986738 0.        ]

In [204]:
similarity[0][:10]

array([1.        , 0.06302535, 0.06554735, 0.04206101, 0.27101851,
       0.13157895, 0.03476173, 0.11561466, 0.03311331, 0.09462916])

In [205]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])

[(0, np.float64(0.9999999999999997)),
 (2405, np.float64(0.516567619255367)),
 (3160, np.float64(0.4111032083956732)),
 (4336, np.float64(0.4055535528269063)),
 (1533, np.float64(0.38807121827489494)),
 (838, np.float64(0.3776782946782564)),
 (2017, np.float64(0.37191715263086833)),
 (373, np.float64(0.3658637387110722)),
 (1916, np.float64(0.35840861465369933)),
 (461, np.float64(0.3434147975799544)),
 (305, np.float64(0.33648809349402886)),
 (2200, np.float64(0.3363311128027263)),
 (2968, np.float64(0.3297851174389325)),
 (1080, np.float64(0.32780503405359285)),
 (661, np.float64(0.32540701330914323)),
 (1711, np.float64(0.3251662385715449)),
 (300, np.float64(0.32481131806711666)),
 (278, np.float64(0.3216009523969407)),
 (1214, np.float64(0.32158761358609866)),
 (577, np.float64(0.3213422934585757)),
 (158, np.float64(0.31788776569561045)),
 (1355, np.float64(0.315334885836572)),
 (3536, np.float64(0.31360753782198686)),
 (507, np.float64(0.3130107162734597)),
 (184, np.float64(0.30110815070511227)),
 (1319, np.float64(0.2973773571300608)),
 (47, np.float64(0.29682979642880863)),
 (3734, np.float64(0.29373674772302333)),
 (1353, np.float64(0.29139711855430955)),
 (149, np.float64(0.2896811091620759)),
 (260, np.float64(0.2845551966122361)),
 (1202, np.float64(0.2845551966122361)),
 (1069, np.float64(0.2844931501972937)),
 (1953, np.float64(0.28392415310581703)),
 (94, np.float64(0.2831969301619155)),
 (239, np.float64(0.2809757434745082)),
 (778, np.float64(0.28027592733560525)),
 (582, np.float64(0.2750598021100904)),
 (539, np.float64(0.2720535937912544)),
 (4, np.float64(0.2710185097828253)),
 (972, np.float64(0.26294249557814203)),
 (3671, np.float64(0.25828827832167467)),
 (1761, np.float64(0.2568505834570407)),
 (1978, np.float64(0.2545139051903111)),
 (4046, np.float64(0.25391668753850405)),
 (2878, np.float64(0.25387276871303704)),
 (95, np.float64(0.2523573072576179)),
 (322, np.float64(0.24999999999999994)),
 (502, np.float64(0.24999999999999992)),
 (595, np.float64(0.24967623556456983)),
 (541, np.float64(0.2488363008967197)),
 (74, np.float64(0.24333213169614382)),
 (1087, np.float64(0.24333213169614376)),
 (2969, np.float64(0.24318019154289874)),
 (61, np.float64(0.24190495145855573)),
 (56, np.float64(0.23961691914926153)),
 (1342, np.float64(0.2369395511036369)),
 (1199, np.float64(0.2357797812857538)),
 (52, np.float64(0.23498939817841863)),
 (643, np.float64(0.23498939817841863)),
 (1054, np.float64(0.23498939817841863)),
 (549, np.float64(0.23308661869922598)),
 (1218, np.float64(0.23230157981385027)),
 (432, np.float64(0.22981367993524693)),
 (770, np.float64(0.22973414586817037)),
 (67, np.float64(0.22941573387056174)),
 (3407, np.float64(0.22941573387056174)),
 (1961, np.float64(0.22722331478659644)),
 (150, np.float64(0.22605003945421215)),
 (2697, np.float64(0.22591299788996197)),
 (581, np.float64(0.22480720075647426)),
 (1992, np.float64(0.22395267080704775)),
 (3145, np.float64(0.21882153700534207)),
 (83, np.float64(0.21677749238102995)),
 (692, np.float64(0.21667041532219716)),
 (754, np.float64(0.21629522817435004)),
 (1276, np.float64(0.21179343552183932)),
 (1369, np.float64(0.20991342856239584)),
 (3997, np.float64(0.2094269541458477)),
 (787, np.float64(0.20780973338645242)),
 (91, np.float64(0.20751433915982234)),
 (773, np.float64(0.2074364287612964)),
 (228, np.float64(0.20732210721568228)),
 (41, np.float64(0.20565318641515562)),
 (236, np.float64(0.20561572340611634)),
 (27, np.float64(0.20519567041703077)),
 (1029, np.float64(0.20295302744752147)),
 (342, np.float64(0.20063458647036803)),
 (270, np.float64(0.20001778014849936)),
 (557, np.float64(0.19767387315371673)),
 (2936, np.float64(0.19751456577539828)),
 (2543, np.float64(0.19619314913492367)),
 (2914, np.float64(0.19332886183313758)),
 (230, np.float64(0.19214253353608038)),
 (4190, np.float64(0.19170644527903724)),
 (454, np.float64(0.19058646954106548)),
 (3606, np.float64(0.19031442722792258)),
 (1475, np.float64(0.19001047197680243)),
 (1000, np.float64(0.1888623619372046)),
 (1484, np.float64(0.18857857160117852)),
 (3626, np.float64(0.18787382673022596)),
 (1652, np.float64(0.1866272256725398)),
 (2580, np.float64(0.18608073189119673)),
 (168, np.float64(0.18560646746692377)),
 (1295, np.float64(0.18560646746692377)),
 (1327, np.float64(0.18560646746692377)),
 (4596, np.float64(0.1835325870964494)),
 (889, np.float64(0.18251335818524614)),
 (579, np.float64(0.18232113763882918)),
 (740, np.float64(0.18067900652188354)),
 (1278, np.float64(0.17971268936194615)),
 (1492, np.float64(0.17938682746310244)),
 (1283, np.float64(0.17801291102397054)),
 (1664, np.float64(0.17668545570588975)),
 (1176, np.float64(0.17624204863381399)),
 (306, np.float64(0.17492785713532988)),
 (480, np.float64(0.1748149640244195)),
 (2329, np.float64(0.17481496402441948)),
 (2861, np.float64(0.1733487427953661)),
 (626, np.float64(0.1720618004029213)),
 (4405, np.float64(0.1720618004029213)),
 (4112, np.float64(0.1717073987899772)),
 (4343, np.float64(0.1712078904153948)),
 (87, np.float64(0.17099639201419237)),
 (2782, np.float64(0.17099639201419234)),
 (1924, np.float64(0.17013926184468015)),
 (2446, np.float64(0.17013926184468012)),
 (26, np.float64(0.1699382703252007)),
 (46, np.float64(0.16816555640136316)),
 (249, np.float64(0.16754156331667816)),
 (1320, np.float64(0.16742770563222897)),
 (1379, np.float64(0.1657104529998322)),
 (2484, np.float64(0.1656806891104139)),
 (4468, np.float64(0.1656806891104139)),
 (564, np.float64(0.16563698349810532)),
 (111, np.float64(0.16427061504961218)),
 (2231, np.float64(0.1632321562747526)),
 (1556, np.float64(0.16289594138375038)),
 (680, np.float64(0.16289594138375035)),
 (35, np.float64(0.16222142113076252)),
 (1273, np.float64(0.16122923187750418)),
 (2511, np.float64(0.16122923187750418)),
 (2783, np.float64(0.16122923187750418)),
 (3070, np.float64(0.16122923187750418)),
 (855, np.float64(0.1611064840623164)),
 (3325, np.float64(0.16059101370939324)),
 (4353, np.float64(0.16059101370939322)),
 (108, np.float64(0.16024705035571787)),
 (466, np.float64(0.15974461276617435)),
 (3216, np.float64(0.15974461276617435)),
 (222, np.float64(0.15806712450288418)),
 (36, np.float64(0.1577233170360112)),
 (3908, np.float64(0.1577233170360112)),
 (223, np.float64(0.1575633729158136)),
 (1440, np.float64(0.1574724447330466)),
 (3728, np.float64(0.1574724447330466)),
 (200, np.float64(0.15743507142179688)),
 (931, np.float64(0.15743507142179688)),
 (4664, np.float64(0.15743507142179688)),
 (233, np.float64(0.1573778950729267)),
 (843, np.float64(0.15609763526361564)),
 (942, np.float64(0.15609763526361564)),
 (2435, np.float64(0.15597978123755524)),
 (3447, np.float64(0.1556357543698668)),
 (1081, np.float64(0.15531518604934885)),
 (2552, np.float64(0.15486771987590017)),
 (141, np.float64(0.15467205622243646)),
 (2055, np.float64(0.15328483487124145)),
 (14, np.float64(0.15301409312053071)),
 (2018, np.float64(0.15301409312053071)),
 (3429, np.float64(0.15174424466672098)),
 (1392, np.float64(0.1508123367044475)),
 (101, np.float64(0.14974651178226578)),
 (1879, np.float64(0.14974651178226578)),
 (2816, np.float64(0.14974651178226578)),
 (617, np.float64(0.14838017169334217)),
 (229, np.float64(0.1476510263878828)),
 (2758, np.float64(0.14748154320250398)),
 (1770, np.float64(0.14694367167412897)),
 (1462, np.float64(0.14659886790209342)),
 (3628, np.float64(0.1456985592771548)),
 (1442, np.float64(0.14567913668701624)),
 (2672, np.float64(0.14567913668701624)),
 (156, np.float64(0.14539227233904237)),
 (1107, np.float64(0.14509525002200233)),
 (2900, np.float64(0.14350946197048195)),
 (529, np.float64(0.14316407166955)),
 (3753, np.float64(0.14316407166954997)),
 (642, np.float64(0.14227759830611805)),
 (1035, np.float64(0.14180703562423225)),
 (2727, np.float64(0.14159846508095772)),
 (1375, np.float64(0.1415386558005362)),
 (3186, np.float64(0.14119562368122623)),
 (127, np.float64(0.1404878717372541)),
 (628, np.float64(0.1404878717372541)),
 (401, np.float64(0.14048787173725408)),
 (3817, np.float64(0.14048787173725408)),
 (483, np.float64(0.1399422857082639)),
 (2785, np.float64(0.1399422857082639)),
 (1566, np.float64(0.13920485060019283)),
 (31, np.float64(0.1391037210186643)),
 (1999, np.float64(0.1391037210186643)),
 (1359, np.float64(0.13904693239779645)),
 (232, np.float64(0.13834289277321493)),
 (800, np.float64(0.13834289277321493)),
 (587, np.float64(0.13809204416652687)),
 (185, np.float64(0.13795635138411733)),
 (2343, np.float64(0.1379563513841173)),
 (1752, np.float64(0.13679711361135388)),
 (2205, np.float64(0.13674085322912188)),
 (487, np.float64(0.13572417850765922)),
 (1520, np.float64(0.13572417850765922)),
 (1741, np.float64(0.1357241785076592)),
 (3726, np.float64(0.13497638119975425)),
 (1095, np.float64(0.13440323049513725)),
 (3100, np.float64(0.1338548962820509)),
 (1654, np.float64(0.1338258447578277)),
 (2054, np.float64(0.1338258447578277)),
 (365, np.float64(0.13300397918683543)),
 (2165, np.float64(0.13245323570650439)),
 (4545, np.float64(0.13227116931706748)),
 (2997, np.float64(0.132005000120825)),
 (1164, np.float64(0.13200500012082497)),
 (5, np.float64(0.13157894736842102)),
 (220, np.float64(0.13109470506889243)),
 (1017, np.float64(0.13072174640400053)),
 (505, np.float64(0.1302565123238377)),
 (3363, np.float64(0.1302565123238377)),
 (490, np.float64(0.13006649542861798)),
 (2756, np.float64(0.13006649542861795)),
 (1013, np.float64(0.12988108336653276)),
 (1292, np.float64(0.12988108336653276)),
 (1737, np.float64(0.1294565671184089)),
 (456, np.float64(0.1290564332299168)),
 (3233, np.float64(0.1284985132406471)),
 (939, np.float64(0.12835876495216744)),
 (2539, np.float64(0.12824729401064425)),
 (169, np.float64(0.12780429685269148)),
 (2131, np.float64(0.1274596880313134)),
 (110, np.float64(0.1274531854836454)),
 (755, np.float64(0.1274531854836454)),
 (3903, np.float64(0.1274531854836454)),
 (1585, np.float64(0.12725695259515554)),
 (2243, np.float64(0.12725695259515554)),
 (3957, np.float64(0.12725695259515554)),
 (585, np.float64(0.12707606131310362)),
 (18, np.float64(0.12671658092865348)),
 (311, np.float64(0.1260506983326509)),
 (1235, np.float64(0.1260506983326509)),
 (2071, np.float64(0.1260506983326509)),
 (1441, np.float64(0.12590824129146974)),
 (2652, np.float64(0.12565617248750865)),
 (151, np.float64(0.12540051368250324)),
 (267, np.float64(0.12540051368250324)),
 (878, np.float64(0.12540051368250324)),
 (3441, np.float64(0.1251933489167979)),
 (3439, np.float64(0.12519334891679787)),
 (1414, np.float64(0.12519334891679784)),
 (1159, np.float64(0.12487810821089251)),
 (2759, np.float64(0.1243275216998167)),
 (207, np.float64(0.12428283974987417)),
 (473, np.float64(0.12428283974987417)),
 (3193, np.float64(0.12361284651454937)),
 (1192, np.float64(0.12339191184909337)),
 (1494, np.float64(0.12297974198582043)),
 (3289, np.float64(0.12262786789699315)),
 (3115, np.float64(0.1222789970111296)),
 (430, np.float64(0.1216660658480719)),
 (279, np.float64(0.12166606584807188)),
 (3210, np.float64(0.12154742509255279)),
 (1525, np.float64(0.12141546606429567)),
 (362, np.float64(0.12105003117656304)),
 (599, np.float64(0.12105003117656304)),
 (72, np.float64(0.12049504662575557)),
 (1645, np.float64(0.12049504662575557)),
 (1189, np.float64(0.12024651756097043)),
 (1827, np.float64(0.12001066808909962)),
 (208, np.float64(0.11980845957463077)),
 (138, np.float64(0.11969747440993465)),
 (1934, np.float64(0.11946953821789977)),
 (4176, np.float64(0.1186988926131663)),
 (419, np.float64(0.11846977555181845)),
 (2031, np.float64(0.11846977555181845)),
 (568, np.float64(0.1183892660110542)),
 (1717, np.float64(0.11838926601105419)),
 (2938, np.float64(0.11831213107007524)),
 (1417, np.float64(0.11803342130469505)),
 (2452, np.float64(0.11803342130469503)),
 (785, np.float64(0.11768778828946261)),
 (1016, np.float64(0.11749469908920933)),
 (4325, np.float64(0.11749469908920933)),
 (275, np.float64(0.11712303424679454)),
 (870, np.float64(0.11615078990692514)),
 (7, np.float64(0.11561466260321597)),
 (2916, np.float64(0.11561466260321597)),
 (4512, np.float64(0.11561466260321597)),
 (1099, np.float64(0.11542256460957982)),
 (3613, np.float64(0.1152857439776791)),
 (2886, np.float64(0.11518482478021624)),
 (495, np.float64(0.11470786693528087)),
 (524, np.float64(0.11470786693528087)),
 (1291, np.float64(0.11470786693528087)),
 (1789, np.float64(0.11470786693528087)),
 (3554, np.float64(0.11400628318608147)),
 (3570, np.float64(0.11382207864489444)),
 (206, np.float64(0.11357771260606368)),
 (2728, np.float64(0.11357771260606367)),
 (3819, np.float64(0.11355499479153376)),
 (1297, np.float64(0.11331741716232277)),
 (256, np.float64(0.11314714296070713)),
 (3754, np.float64(0.11314714296070712)),
 (102, np.float64(0.11264088922239573)),
 (363, np.float64(0.11264088922239573)),
 (589, np.float64(0.11264088922239573)),
 (633, np.float64(0.11264088922239573)),
 (1798, np.float64(0.11264088922239573)),
 (1037, np.float64(0.11243619908556621)),
 (3312, np.float64(0.11243619908556621)),
 (4316, np.float64(0.11211037093424209)),
 (3670, np.float64(0.11164843913471803)),
 (3768, np.float64(0.11164843913471803)),
 (172, np.float64(0.11134983352076111)),
 (2280, np.float64(0.11128297681493145)),
 (1407, np.float64(0.1108922805469306)),
 (107, np.float64(0.1106817677872384)),
 (1463, np.float64(0.11047363533322148)),
 (2174, np.float64(0.11037769642208697)),
 (3779, np.float64(0.11037769642208697)),
 (4587, np.float64(0.11037769642208697)),
 (70, np.float64(0.11029436104106954)),
 (1925, np.float64(0.11029436104106953)),
 (459, np.float64(0.11020775375559674)),
 (53, np.float64(0.11005109731001664)),
 (462, np.float64(0.10982442127674487)),
 (1613, np.float64(0.10968169942141635)),
 (2902, np.float64(0.10968169942141634)),
 (147, np.float64(0.10926834468453095)),
 (1090, np.float64(0.10926834468453095)),
 (653, np.float64(0.10882143751650175)),
 (1497, np.float64(0.10838874619051497)),
 (3376, np.float64(0.10838874619051497)),
 (592, np.float64(0.10822186580487339)),
 (4098, np.float64(0.10822186580487339)),
 (536, np.float64(0.10814761408717502)),
 (2792, np.float64(0.10814761408717502)),
 (2869, np.float64(0.10814761408717502)),
 (4095, np.float64(0.10814761408717502)),
 (1470, np.float64(0.1074861545850028)),
 (2714, np.float64(0.10748615458500278)),
 (3179, np.float64(0.10748615458500278)),
 (784, np.float64(0.10740432270821093)),
 (1271, np.float64(0.10740432270821093)),
 (2235, np.float64(0.10740432270821093)),
 (1435, np.float64(0.10740432270821092)),
 (2154, np.float64(0.10729938440986903)),
 (4228, np.float64(0.10729938440986903)),
 (1745, np.float64(0.10729938440986901)),
 (2068, np.float64(0.10729938440986901)),
 (571, np.float64(0.10705186531570646)),
 (813, np.float64(0.10667614941253299)),
 (4473, np.float64(0.10650358071057624)),
 (2129, np.float64(0.10596258856520348)),
 (995, np.float64(0.10591900946051636)),
 (1570, np.float64(0.10591900946051636)),
 (3808, np.float64(0.10588418486333619)),
 (413, np.float64(0.10543316579753613)),
 (1635, np.float64(0.10526315789473682)),
 (1824, np.float64(0.10526315789473682)),
 (2876, np.float64(0.10526315789473682)),
 (3006, np.float64(0.10495671428119792)),
 (215, np.float64(0.10482137352305541)),
 (3157, np.float64(0.10471347707292386)),
 (1997, np.float64(0.10457739712320041)),
 (4152, np.float64(0.10457739712320041)),
 (10, np.float64(0.1045358459406623)),
 (3352, np.float64(0.1045358459406623)),
 (1893, np.float64(0.1039048666932262)),
 (389, np.float64(0.1037571695799112)),
 (371, np.float64(0.10366105360784116)),
 (1610, np.float64(0.10366105360784116)),
 (1894, np.float64(0.10324514658393345)),
 (2494, np.float64(0.10324514658393345)),
 (476, np.float64(0.10301070542879114)),
 (2899, np.float64(0.10280786170305815)),
 (16, np.float64(0.10280786170305814)),
 (422, np.float64(0.10259783520851543)),
 (3535, np.float64(0.10259783520851541)),
 (17, np.float64(0.1025978352085154)),
 (1040, np.float64(0.1025978352085154)),
 (2429, np.float64(0.1025978352085154)),
 (4179, np.float64(0.1025978352085154)),
 (790, np.float64(0.10221994134545731)),
 (3516, np.float64(0.10147651372376075)),
 (404, np.float64(0.10147651372376074)),
 (632, np.float64(0.10147651372376074)),
 (2988, np.float64(0.10147651372376074)),
 (3762, np.float64(0.10147651372376074)),
 (900, np.float64(0.10116282977781398)),
 (3412, np.float64(0.10116282977781398)),
 (400, np.float64(0.10039117221153819)),
 (1764, np.float64(0.10039117221153818)),
 (3620, np.float64(0.10036938356837077)),
 (4694, np.float64(0.10036938356837076)),
 (768, np.float64(0.10012523486435176)),
 (3020, np.float64(0.10012523486435176)),
 (4008, np.float64(0.10012523486435176)),
 (1272, np.float64(0.09984038297885897)),
 (2319, np.float64(0.09984038297885897)),
 (2502, np.float64(0.09984038297885897)),
 (3719, np.float64(0.09984038297885897)),
 (3091, np.float64(0.09959431881428264)),
 (1508, np.float64(0.09959431881428263)),
 (3496, np.float64(0.09959431881428263)),
 (2177, np.float64(0.09933992677987828)),
 (586, np.float64(0.09895413919905867)),
 (814, np.float64(0.09883693657685835)),
 (51, np.float64(0.09838379358865636)),
 (660, np.float64(0.0983611844205792)),
 (1169, np.float64(0.0983611844205792)),
 (3374, np.float64(0.0983611844205792)),
 (166, np.float64(0.09832102880166932)),
 (1111, np.float64(0.09832102880166932)),
 (174, np.float64(0.09809657456746185)),
 (1062, np.float64(0.09809657456746183)),
 (420, np.float64(0.09782319760890368)),
 (4348, np.float64(0.09782319760890368)),
 (412, np.float64(0.09737260471306503)),
 (1527, np.float64(0.097372604713065)),
 (187, np.float64(0.09733285267845751)),
 (978, np.float64(0.09733285267845751)),
 (4077, np.float64(0.09733285267845751)),
 (2049, np.float64(0.09694584179118515)),
 (2287, np.float64(0.09694584179118515)),
 (3657, np.float64(0.09694584179118515)),
 (3714, np.float64(0.09694584179118515)),
 (4254, np.float64(0.09694584179118515)),
 (794, np.float64(0.09666443091656879)),
 (666, np.float64(0.09637388493048532)),
 (1136, np.float64(0.09637388493048532)),
 (4203, np.float64(0.09637388493048532)),
 (4602, np.float64(0.09637388493048532)),
 (246, np.float64(0.09619721404877635)),
 (4600, np.float64(0.0959714869937393)),
 (4163, np.float64(0.09567297464698797)),
 (4276, np.float64(0.09567297464698797)),
 (4333, np.float64(0.09567297464698797)),
 (935, np.float64(0.09558988911273406)),
 (1938, np.float64(0.09558988911273406)),
 (3287, np.float64(0.09558988911273406)),
 (330, np.float64(0.09544271444636666)),
 (1084, np.float64(0.09544271444636666)),
 (2440, np.float64(0.09544271444636666)),
 (329, np.float64(0.09544271444636665)),
 (687, np.float64(0.09544271444636665)),
 (1032, np.float64(0.09544271444636665)),
 (3416, np.float64(0.09544271444636665)),
 (3172, np.float64(0.09462916232627815)),
 (9, np.float64(0.09462916232627813)),
 (1410, np.float64(0.09462916232627813)),
 (37, np.float64(0.09453802374948818)),
 (859, np.float64(0.09453802374948818)),
 (438, np.float64(0.09453802374948816)),
 (1820, np.float64(0.09453802374948816)),
 (3035, np.float64(0.09453802374948816)),
 (4731, np.float64(0.09453802374948816)),
 (4016, np.float64(0.09428928580058928)),
 (4196, np.float64(0.09428928580058928)),
 (4234, np.float64(0.09428928580058928)),
 (253, np.float64(0.09415023063157009)),
 (1674, np.float64(0.09415023063157009)),
 (2444, np.float64(0.09404801560780579)),
 (30, np.float64(0.09397878236968457)),
 (48, np.float64(0.09397878236968456)),
 (897, np.float64(0.0936585811581694)),
 (1669, np.float64(0.0936585811581694)),
 (39, np.float64(0.09365858115816939)),
 (271, np.float64(0.09365858115816939)),
 (1322, np.float64(0.09365858115816939)),
 (4270, np.float64(0.09365858115816939)),
 (531, np.float64(0.09334163073596637)),
 (1166, np.float64(0.09334163073596637)),
 (307, np.float64(0.09308574042571362)),
 (1066, np.float64(0.09304036594559836)),
 (294, np.float64(0.09304036594559835)),

In [206]:
def recomended(movie):
    movie_index= new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [207]:
new_df['title']=new_df['title'].apply(lambda x:x[0] if isinstance(x,list)else x)

C:\Users\acer\AppData\Local\Temp\ipykernel_19744\2656108857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title']=new_df['title'].apply(lambda x:x[0] if isinstance(x,list)else x)

In [208]:
distance =sorted(list(enumerate(similarity[0])),
                 reverse=True,key=lambda x:x[1]
             )[1:6]
print(distance[:10])

[(2405, np.float64(0.516567619255367)), (3160, np.float64(0.4111032083956732)), (4336, np.float64(0.4055535528269063)), (1533, np.float64(0.38807121827489494)), (838, np.float64(0.3776782946782564))]

In [209]:
recomended("Batman Begins")

The Dark Knight
Batman
The Dark Knight Rises
Batman
Batman & Robin

In [210]:
new_df.iloc[2404].title

'The Others'

In [211]:
import pickle

In [212]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [213]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], shape=(4806,), dtype=object)

In [214]:
new_df.to_dict()

{'movie_id': {0: 19995,
  1: 285,
  2: 206647,
  3: 49026,
  4: 49529,
  5: 559,
  6: 38757,
  7: 99861,
  8: 767,
  9: 209112,
  10: 1452,
  11: 10764,
  12: 58,
  13: 57201,
  14: 49521,
  15: 2454,
  16: 24428,
  17: 1865,
  18: 41154,
  19: 122917,
  20: 1930,
  21: 20662,
  22: 57158,
  23: 2268,
  24: 254,
  25: 597,
  26: 271110,
  27: 44833,
  28: 135397,
  29: 37724,
  30: 558,
  31: 68721,
  32: 12155,
  33: 36668,
  34: 62211,
  35: 8373,
  36: 91314,
  37: 68728,
  38: 102382,
  39: 20526,
  40: 49013,
  41: 44912,
  42: 10193,
  43: 534,
  44: 168259,
  45: 72190,
  46: 127585,
  47: 54138,
  48: 81005,
  49: 64682,
  50: 9543,
  51: 68726,
  52: 38356,
  53: 217,
  54: 105864,
  55: 62177,
  56: 188927,
  57: 10681,
  58: 5174,
  59: 14161,
  60: 17979,
  61: 76757,
  62: 258489,
  63: 411,
  64: 246655,
  65: 155,
  66: 14160,
  67: 15512,
  68: 1726,
  69: 44826,
  70: 8487,
  71: 1735,
  72: 297761,
  73: 2698,
  74: 137113,
  75: 9804,
  76: 14869,
  77: 150540,
  78: 278927,
  79: 10138,
  80: 58595,
  81: 102651,
  82: 119450,
  83: 79698,
  84: 64686,
  85: 100402,
  86: 10192,
  87: 158852,
  88: 177572,
  89: 82690,
  90: 5255,
  91: 47933,
  92: 10191,
  93: 296,
  94: 118340,
  95: 157336,
  96: 27205,
  97: 315011,
  98: 49051,
  99: 9799,
  100: 4922,
  101: 49538,
  102: 131634,
  103: 27022,
  104: 503,
  105: 241259,
  106: 810,
  107: 68735,
  108: 87101,
  109: 10140,
  110: 676,
  111: 1858,
  112: 1966,
  113: 675,
  114: 674,
  115: 8960,
  116: 6479,
  117: 118,
  118: 2062,
  119: 272,
  120: 10527,
  121: 18360,
  122: 2080,
  123: 605,
  124: 109445,
  125: 604,
  126: 76338,
  127: 76341,
  128: 13448,
  129: 10195,
  130: 13053,
  131: 19585,
  132: 57165,
  133: 62213,
  134: 177677,
  135: 7978,
  136: 5559,
  137: 49444,
  138: 10196,
  139: 956,
  140: 117251,
  141: 50321,
  142: 11619,
  143: 266647,
  144: 82703,
  145: 652,
  146: 80321,
  147: 36669,
  148: 43074,
  149: 95,
  150: 608,
  151: 2310,
  152: 140300,
  153: 56292,
  154: 81188,
  155: 7552,
  156: 616,
  157: 147441,
  158: 13475,
  159: 557,
  160: 82702,
  161: 205584,
  162: 10048,
  163: 13183,
  164: 944,
  165: 1927,
  166: 72559,
  167: 7364,
  168: 2114,
  169: 1771,
  170: 36643,
  171: 8619,
  172: 50620,
  173: 65759,
  174: 1724,
  175: 267935,
  176: 281957,
  177: 77950,
  178: 44896,
  179: 270946,
  180: 2503,
  181: 9502,
  182: 102899,
  183: 101299,
  184: 228161,
  185: 74,
  186: 8961,
  187: 417859,
  188: 27576,
  189: 86834,
  190: 17578,
  191: 673,
  192: 6972,
  193: 82700,
  194: 10567,
  195: 181533,
  196: 38055,
  197: 671,
  198: 49524,
  199: 22,
  200: 131631,
  201: 591,
  202: 172385,
  203: 36658,
  204: 51497,
  205: 58574,
  206: 18823,
  207: 861,
  208: 1911,
  209: 49040,
  210: 415,
  211: 8871,
  212: 435,
  213: 955,
  214: 2133,
  215: 1979,
  216: 87827,
  217: 1250,
  218: 324668,
  219: 9471,
  220: 70981,
  221: 10996,
  222: 68724,
  223: 2789,
  224: 97020,
  225: 7459,
  226: 42888,
  227: 37834,
  228: 75612,
  229: 1895,
  230: 1894,
  231: 585,
  232: 76170,
  233: 1893,
  234: 49519,
  235: 2395,
  236: 12100,
  237: 290595,
  238: 98566,
  239: 49047,
  240: 9619,
  241: 308531,
  242: 166424,
  243: 1593,
  244: 254128,
  245: 714,
  246: 2024,
  247: 163,
  248: 787,
  249: 262500,
  250: 2567,
  251: 38745,
  252: 40805,
  253: 53182,
  254: 41513,
  255: 13700,
  256: 262504,
  257: 39254,
  258: 77931,
  259: 1639,
  260: 80274,
  261: 1571,
  262: 120,
  263: 10204,
  264: 8489,
  265: 10588,
  266: 2048,
  267: 1495,
  268: 10137,
  269: 10198,
  270: 286217,
  271: 1635,
  272: 24113,
  273: 9679,
  274: 98,
  275: 180,
  276: 672,
  277: 36557,
  278: 869,
  279: 280,
  280: 11322,
  281: 4982,
  282: 36955,
  283: 18487,
  284: 39451,
  285: 27581,
  286: 9268,
  287: 68718,
  288: 10545,
  289: 11688,
  290: 76163,
  291: 2059,
  292: 2486,
  293: 16523,
  294: 116711,
  295: 37710,
  296: 9946,
  297: 1372,
  298: 106646,
  299: 414,
  300: 563,
  301: 83542,
  302: 41216,
  303: 314,
  304: 184315,
  305: 9016,
  306: 18162,
  307: 138103,
  308: 257088,
  309: 10214,
  310: 205775,
  311: 11692,
  312: 22972,
  313: 227973,
  314: 29193,
  315: 1734,
  316: 3131,
  317: 76758,
  318: 9408,
  319: 9890,
  320: 855,
  321: 77953,
  322: 18,
  323: 37786,
  324: 10501,
  325: 57800,
  326: 150689,
  327: 7980,
  328: 12,
  329: 122,
  330: 121,
  331: 68737,
  332: 1995,
  333: 157353,
  334: 331,
  335: 61791,
  336: 8204,
  337: 47964,
  338: 10733,
  339: 9806,
  340: 1408,
  341: 32657,
  342: 607,
  343: 863,
  344: 44048,
  345: 5175,
  346: 2655,
  347: 22794,
  348: 8355,
  349: 116745,
  350: 4327,
  351: 1422,
  352: 10674,
  353: 7446,
  354: 65754,
  355: 1572,
  356: 10528,
  357: 271969,
  358: 10865,
  359: 258509,
  360: 2253,
  361: 10661,
  362: 257344,
  363: 644,
  364: 10756,
  365: 686,
  366: 9383,
  367: 179,
  368: 76285,
  369: 1996,
  370: 291805,
  371: 10003,
  372: 1535,
  373: 2067,
  374: 46195,
  375: 2277,
  376: 10357,
  377: 4477,
  378: 8665,
  379: 9387,
  380: 921,
  381: 49852,
  382: 4464,
  383: 664,
  384: 8358,
  385: 9836,
  386: 2502,
  387: 9772,
  388: 161,
  389: 52451,
  390: 76492,
  391: 4523,
  392: 59961,
  393: 10481,
  394: 59108,
  395: 1581,
  396: 9798,
  397: 22897,
  398: 298,
  399: 7484,
  400: 157350,
  401: 853,
  402: 10159,
  403: 9593,
  404: 1904,
  405: 9615,
  406: 51052,
  407: 297,
  408: 9884,
  409: 16858,
  410: 62764,
  411: 22538,
  412: 9341,
  413: 12107,
  414: 9637,
  415: 49049,
  416: 9339,
  417: 16281,
  418: 39691,
  419: 8247,
  420: 11253,
  421: 1949,
  422: 8452,
  423: 310,
  424: 27578,
  425: 954,
  426: 70160,
  427: 45243,
  428: 364,
  429: 7518,
  430: 11544,
  431: 9986,
  432: 8656,
  433: 146216,
  434: 9291,
  435: 55301,
  436: 109418,
  437: 11665,
  438: 6964,
  439: 11324,
  440: 12193,
  441: 9928,
  442: 754,
  443: 10202,
  444: 4147,
  445: 50546,
  446: 1701,
  447: 13027,
  448: 2289,
  449: 20504,
  450: 9574,
  451: 11618,
  452: 2300,
  453: 12096,
  454: 10200,
  455: 8834,
  456: 228150,
  457: 6068,
  458: 41515,
  459: 9023,
  460: 38317,
  461: 2157,
  462: 14462,
  463: 161795,
  464: 159824,
  465: 49948,
  466: 2135,
  467: 9822,
  468: 9705,
  469: 1656,
  470: 12159,
  471: 9678,
  472: 4442,
  473: 75,
  474: 330770,
  475: 9433,
  476: 19959,
  477: 11973,
  478: 11228,
  479: 77951,
  480: 5491,
  481: 10715,
  482: 10197,
  483: 9562,
  484: 9922,
  485: 9447,
  486: 274854,
  487: 8870,
  488: 9992,
  489: 36970,
  490: 10077,
  491: 76649,
  492: 293644,
  493: 453,
  494: 8587,
  495: 72545,
  496: 109451,
  497: 9533,
  498: 2023,
  499: 71880,
  500: 584,
  501: 309809,
  502: 4858,
  503: 17711,
  504: 328111,
  505: 8698,
  506: 93456,
  507: 602,
  508: 330,
  509: 953,
  510: 9693,
  511: 36657,
  512: 8909,
  513: 9802,
  514: 950,
  515: 1824,
  516: 2976,
  517: 11026,
  518: 332,
  519: 75656,
  520: 38365,
  521: 594,
  522: 15189,
  523: 11678,
  524: 6538,
  525: 10555,
  526: 1125,
  527: 4551,
  528: 612,
  529: 9567,
  530: 37821,
  531: 203801,
  532: 2539,
  533: 9297,
  534: 3172,
  535: 6520,
  536: 1439,
  537: 37958,
  538: 2026,
  539: 7450,
  540: 11375,
  541: 9425,
  542: 25769,
  543: 23685,
  544: 11866,
  545: 9741,
  546: 211672,
  547: 23629,
  548: 8688,
  549: 10153,
  550: 153518,
  551: 8676,
  552: 20829,
  553: 4349,
  554: 9718,
  555: 10808,
  556: 197,
  557: 25,
  558: 35,
  559: 11086,
  560: 10477,
  561: 1997,
  562: 6947,
  563: 3050,
  564: 2675,
  565: 809,
  566: 920,
  567: 4806,
  568: 7451,
  569: 228165,
  570: 3595,
  571: 16869,
  572: 879,
  573: 1573,
  574: 9257,
  575: 1903,
  576: 9697,
  577: 395,
  578: 23398,
  579: 10590,
  580: 117263,
  581: 200,
  582: 44943,
  583: 587,
  584: 10395,
  585: 57212,
  586: 152760,
  587: 2756,
  588: 33909,
  589: 49017,
  590: 9882,
  591: 2270,
  592: 978,
  593: 44564,
  594: 3132,
  595: 8814,
  596: 8427,
  597: 52520,
  598: 80585,
  599: 10592,
  600: 49021,
  601: 11535,
  602: 10550,
  603: 11258,
  604: 12610,
  605: 59981,
  606: 201088,
  607: 5137,
  608: 3093,
  609: 107846,
  610: 188207,
  611: 4614,
  612: 24021,
  613: 11371,
  614: 20352,
  615: 11517,
  616: 214756,
  617: 26428,
  618: 9824,
  619: 48988,
  620: 9008,
  621: 300673,
  622: 12113,
  623: 38778,
  624: 72331,
  625: 1844,
  626: 846,
  627: 9703,
  628: 857,
  629: 136797,
  630: 3981,
  631: 425,
  632: 6171,
  633: 72976,
  634: 603,
  635: 568,
  636: 9021,
  637: 82695,
  638: 9489,
  639: 12133,
  640: 9342,
  641: 41733,
  642: 227306,
  643: 5551,
  644: 9350,
  645: 9208,
  646: 4244,
  647: 1852,
  648: 11820,
  649: 76493,
  650: 345,
  651: 196867,
  652: 256591,
  653: 59962,
  654: 36648,
  655: 1880,
  656: 9440,
  657: 71679,
  658: 10483,
  659: 11412,
  660: 11983,
  661: 6795,
  662: 550,
  663: 11170,
  664: 9292,
  665: 10783,
  666: 100241,
  667: 257,
  668: 9947,
  669: 189,
  670: 12618,
  671: 253412,
  672: 1427,
  673: 818,
  674: 16577,
  675: 329,
  676: 12160,
  677: 9331,
  678: 300168,
  679: 9072,
  680: 3536,
  681: 9087,
  682: 12177,
  683: 12138,
  684: 273248,
  685: 9955,
  686: 50359,
  687: 1271,
  688: 693,
  689: 14306,
  690: 497,
  691: 11199,
  692: 9982,
  693: 210577,
  694: 2501,
  695: 710,
  696: 2275,
  697: 37165,
  698: 9837,
  699: 10708,
  700: 136400,
  701: 10992,
  702: 9654,
  703: 2642,
  704: 8916,
  705: 19899,
  706: 2119,
  707: 9641,
  708: 294254,
  709: 38167,
  710: 5994,
  711: 39514,
  712: 9563,
  713: 547,
  714: 1538,
  715: 9334,
  716: 11128,
  717: 75780,
  718: 8914,
  719: 13576,
  720: 39538,
  721: 10628,
  722: 14836,
  723: 8645,
  724: 9509,
  725: 10067,
  726: 9384,
  727: 9279,
  728: 1487,
  729: 9422,
  730: 77174,
  731: 4824,
  732: 9620,
  733: 9302,
  734: 10199,
  735: 10771,
  736: 3512,
  737: 137094,
  738: 274479,
  739: 267860,
  740: 8078,
  741: 7485,
  742: 170687,
  743: 6435,
  744: 137106,
  745: 10040,
  746: 6278,
  747: 82682,
  748: 17610,
  749: 22954,
  750: 16995,
  751: 16558,
  752: 9849,
  753: 5820,
  754: 16866,
  755: 201,
  756: 11775,
  757: 87825,
  758: 12201,
  759: 11015,
  760: 9932,
  761: 13389,
  762: 8838,
  763: 17332,
  764: 4958,
  765: 786,
  766: 9513,
  767: 11679,
  768: 38321,
  769: 14411,
  770: 8413,
  771: 10052,
  772: 9676,
  773: 9664,
  774: 2100,
  775: 10384,
  776: 137321,
  777: 123553,
  778: 11260,
  779: 9009,
  780: 11374,
  781: 2309,
  782: 8285,
  783: 210860,
  784: 2312,
  785: 9839,
  786: 381902,
  787: 13922,
  788: 293660,
  789: 9713,
  790: 190859,
  791: 257445,
  792: 9007,
  793: 889,
  794: 1370,
  795: 4942,
  796: 347969,
  797: 24438,
  798: 116741,
  799: 35791,
  800: 72431,
  801: 1813,
  802: 87428,
  803: 8840,
  804: 10589,
  805: 71676,
  806: 1722,
  807: 10022,
  808: 11358,
  809: 13,
  810: 6477,
  811: 1597,
  812: 10530,
  813: 1924,
  814: 9327,
  815: 8488,
  816: 10603,
  817: 8273,
  818: 109424,
  819: 35056,
  820: 8839,
  821: 156022,
  822: 7303,
  823: 8963,
  824: 1402,
  825: 9315,
  826: 8984,
  827: 795,
  828: 24,
  829: 11353,
  830: 393,
  831: 9618,
  832: 9374,
  833: 8584,
  834: 2320,
  835: 58224,
  836: 1729,
  837: 175574,
  838: 8077,
  839: 8818,
  840: 8195,
  841: 10586,
  842: 116149,
  843: 80035,
  844: 10632,
  845: 12117,
  846: 1792,
  847: 13260,
  848: 72197,
  849: 3580,
  850: 12123,
  851: 9566,
  852: 9833,
  853: 4517,
  854: 8202,
  855: 16072,
  856: 34314,
  857: 19724,
  858: 145220,
  859: 14623,
  860: 42297,
  861: 2841,
  862: 802,
  863: 10375,
  864: 36586,
  865: 11321,
  866: 70074,
  867: 242,
  868: 9621,
  869: 1819,
  870: 8536,
  871: 8046,
  872: 1717,
  873: 479,
  874: 9444,
  875: 824,
  876: 11456,
  877: 261023,
  878: 3683,
  879: 22803,
  880: 285923,
  881: 39437,
  882: 1950,
  883: 640,
  884: 97630,
  885: 9767,
  886: 11631,
  887: 32856,
  888: 6519,
  889: 8741,
  890: 49520,
  891: 1850,
  892: 524,
  893: 26389,
  894: 11817,
  895: 2123,
  896: 9907,
  897: 9969,
  898: 18239,
  899: 808,
  900: 38050,
  901: 8367,
  902: 9390,
  903: 72105,
  904: 2898,
  905: 10312,
  906: 109443,
  907: 2022,
  908: 37686,
  909: 462,
  910: 9919,
  911: 187017,
  912: 628,
  913: 10201,
  914: 302699,
  915: 9441,
  916: 274167,
  917: 224141,
  918: 388,
  919: 2112,
  920: 10329,
  921: 74465,
  922: 13811,
  923: 6877,
  924: 10320,
  925: 50646,
  926: 8920,
  927: 13673,
  928: 60308,
  929: 6950,
  930: 225574,
  931: 13836,
  932: 752,
  933: 6038,
  934: 9975,
  935: 11451,
  936: 12103,
  937: 60304,
  938: 2251,
  939: 46529,
  940: 231,
  941: 300671,
  942: 228326,
  943: 9754,
  944: 66,
  945: 4421,
  946: 2649,
  947: 588,
  948: 10393,
  949: 71552,
  950: 9631,
  951: 216282,
  952: 306,
  953: 928,
  954: 205587,
  955: 6623,
  956: 1577,
  957: 9801,
  958: 2116,
  959: 9624,
  960: 14199,
  961: 1907,
  962: 4599,
  963: 22832,
  964: 10390,
  965: 9879,
  966: 38579,
  967: 44603,
  968: 11892,
  969: 9691,
  970: 1248,
  971: 12220,
  972: 72710,
  973: 72710,
  974: 10782,
  975: 9573,
  976: 4959,
  977: 10061,
  978: 10386,
  979: 421,
  980: 316152,
  981: 11615,
  982: 13498,
  983: 241554,
  984: 2252,
  985: 11968,
  986: 10047,
  987: 38319,
  988: 69668,
  989: 9770,
  990: 11212,
  991: 10533,
  992: 38363,
  993: 9923,
  994: 11863,
  995: 18501,
  996: 109491,
  997: 9275,
  998: 329833,
  999: 12634,
  ...},
 'title': {0: 'Avatar',
  1: "Pirates of the Caribbean: At World's End",
  2: 'Spectre',
  3: 'The Dark Knight Rises',
  4: 'John Carter',
  5: 'Spider-Man 3',
  6: 'Tangled',
  7: 'Avengers: Age of Ultron',
  8: 'Harry Potter and the Half-Blood Prince',
  9: 'Batman v Superman: Dawn of Justice',
  10: 'Superman Returns',
  11: 'Quantum of Solace',
  12: "Pirates of the Caribbean: Dead Man's Chest",
  13: 'The Lone Ranger',
  14: 'Man of Steel',
  15: 'The Chronicles of Narnia: Prince Caspian',
  16: 'The Avengers',
  17: 'Pirates of the Caribbean: On Stranger Tides',
  18: 'Men in Black 3',
  19: 'The Hobbit: The Battle of the Five Armies',
  20: 'The Amazing Spider-Man',
  21: 'Robin Hood',
  22: 'The Hobbit: The Desolation of Smaug',
  23: 'The Golden Compass',
  24: 'King Kong',
  25: 'Titanic',
  26: 'Captain America: Civil War',
  27: 'Battleship',
  28: 'Jurassic World',
  29: 'Skyfall',
  30: 'Spider-Man 2',
  31: 'Iron Man 3',
  32: 'Alice in Wonderland',
  33: 'X-Men: The Last Stand',
  34: 'Monsters University',
  35: 'Transformers: Revenge of the Fallen',
  36: 'Transformers: Age of Extinction',
  37: 'Oz: The Great and Powerful',
  38: 'The Amazing Spider-Man 2',
  39: 'TRON: Legacy',
  40: 'Cars 2',
  41: 'Green Lantern',
  42: 'Toy Story 3',
  43: 'Terminator Salvation',
  44: 'Furious 7',
  45: 'World War Z',
  46: 'X-Men: Days of Future Past',
  47: 'Star Trek Into Darkness',
  48: 'Jack the Giant Slayer',
  49: 'The Great Gatsby',
  50: 'Prince of Persia: The Sands of Time',
  51: 'Pacific Rim',
  52: 'Transformers: Dark of the Moon',
  53: 'Indiana Jones and the Kingdom of the Crystal Skull',
  54: 'The Good Dinosaur',
  55: 'Brave',
  56: 'Star Trek Beyond',
  57: 'WALL·E',
  58: 'Rush Hour 3',
  59: '2012',
  60: 'A Christmas Carol',
  61: 'Jupiter Ascending',
  62: 'The Legend of Tarzan',
  63: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  64: 'X-Men: Apocalypse',
  65: 'The Dark Knight',
  66: 'Up',
  67: 'Monsters vs Aliens',
  68: 'Iron Man',
  69: 'Hugo',
  70: 'Wild Wild West',
  71: 'The Mummy: Tomb of the Dragon Emperor',
  72: 'Suicide Squad',
  73: 'Evan Almighty',
  74: 'Edge of Tomorrow',
  75: 'Waterworld',
  76: 'G.I. Joe: The Rise of Cobra',
  77: 'Inside Out',
  78: 'The Jungle Book',
  79: 'Iron Man 2',
  80: 'Snow White and the Huntsman',
  81: 'Maleficent',
  82: 'Dawn of the Planet of the Apes',
  83: 'The Lovers',
  84: '47 Ronin',
  85: 'Captain America: The Winter Soldier',
  86: 'Shrek Forever After',
  87: 'Tomorrowland',
  88: 'Big Hero 6',
  89: 'Wreck-It Ralph',
  90: 'The Polar Express',
  91: 'Independence Day: Resurgence',
  92: 'How to Train Your Dragon',
  93: 'Terminator 3: Rise of the Machines',
  94: 'Guardians of the Galaxy',
  95: 'Interstellar',
  96: 'Inception',
  97: 'Shin Godzilla',
  98: 'The Hobbit: An Unexpected Journey',
  99: 'The Fast and the Furious',
  100: 'The Curious Case of Benjamin Button',
  101: 'X-Men: First Class',
  102: 'The Hunger Games: Mockingjay - Part 2',
  103: "The Sorcerer's Apprentice",
  104: 'Poseidon',
  105: 'Alice Through the Looking Glass',
  106: 'Shrek the Third',
  107: 'Warcraft',
  108: 'Terminator Genisys',
  109: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
  110: 'Pearl Harbor',
  111: 'Transformers',
  112: 'Alexander',
  113: 'Harry Potter and the Order of the Phoenix',
  114: 'Harry Potter and the Goblet of Fire',
  115: 'Hancock',
  116: 'I Am Legend',
  117: 'Charlie and the Chocolate Factory',
  118: 'Ratatouille',
  119: 'Batman Begins',
  120: 'Madagascar: Escape 2 Africa',
  121: 'Night at the Museum: Battle of the Smithsonian',
  122: 'X-Men Origins: Wolverine',
  123: 'The Matrix Revolutions',
  124: 'Frozen',
  125: 'The Matrix Reloaded',
  126: 'Thor: The Dark World',
  127: 'Mad Max: Fury Road',
  128: 'Angels & Demons',
  129: 'Thor',
  130: 'Bolt',
  131: 'G-Force',
  132: 'Wrath of the Titans',
  133: 'Dark Shadows',
  134: 'Mission: Impossible - Rogue Nation',
  135: 'The Wolfman',
  136: 'Bee Movie',
  137: 'Kung Fu Panda 2',
  138: 'The Last Airbender',
  139: 'Mission: Impossible III',
  140: 'White House Down',
  141: 'Mars Needs Moms',
  142: 'Flushed Away',
  143: 'Pan',
  144: 'Mr. Peabody & Sherman',
  145: 'Troy',
  146: "Madagascar 3: Europe's Most Wanted",
  147: 'Die Another Day',
  148: 'Ghostbusters',
  149: 'Armageddon',
  150: 'Men in Black II',
  151: 'Beowulf',
  152: 'Kung Fu Panda 3',
  153: 'Mission: Impossible - Ghost Protocol',
  154: 'Rise of the Guardians',
  155: 'Fun with Dick and Jane',
  156: 'The Last Samurai',
  157: 'Exodus: Gods and Kings',
  158: 'Star Trek',
  159: 'Spider-Man',
  160: 'How to Train Your Dragon 2',
  161: 'Gods of Egypt',
  162: 'Stealth',
  163: 'Watchmen',
  164: 'Lethal Weapon 4',
  165: 'Hulk',
  166: 'G.I. Joe: Retaliation',
  167: 'Sahara',
  168: 'Final Fantasy: The Spirits Within',
  169: 'Captain America: The First Avenger',
  170: 'The World Is Not Enough',
  171: 'Master and Commander: The Far Side of the World',
  172: 'The Twilight Saga: Breaking Dawn - Part 2',
  173: 'Happy Feet Two',
  174: 'The Incredible Hulk',
  175: 'The BFG',
  176: 'The Revenant',
  177: 'Turbo',
  178: 'Rango',
  179: 'Penguins of Madagascar',
  180: 'The Bourne Ultimatum',
  181: 'Kung Fu Panda',
  182: 'Ant-Man',
  183: 'The Hunger Games: Catching Fire',
  184: 'Home',
  185: 'War of the Worlds',
  186: 'Bad Boys II',
  187: 'Puss in Boots',
  188: 'Salt',
  189: 'Noah',
  190: 'The Adventures of Tintin',
  191: 'Harry Potter and the Prisoner of Azkaban',
  192: 'Australia',
  193: 'After Earth',
  194: 'Dinosaur',
  195: 'Night at the Museum: Secret of the Tomb',
  196: 'Megamind',
  197: "Harry Potter and the Philosopher's Stone",
  198: 'R.I.P.D.',
  199: 'Pirates of the Caribbean: The Curse of the Black Pearl',
  200: 'The Hunger Games: Mockingjay - Part 1',
  201: 'The Da Vinci Code',
  202: 'Rio 2',
  203: 'X2',
  204: 'Fast Five',
  205: 'Sherlock Holmes: A Game of Shadows',
  206: 'Clash of the Titans',
  207: 'Total Recall',
  208: 'The 13th Warrior',
  209: 'The Bourne Legacy',
  210: 'Batman & Robin',
  211: 'How the Grinch Stole Christmas',
  212: 'The Day After Tomorrow',
  213: 'Mission: Impossible II',
  214: 'The Perfect Storm',
  215: 'Fantastic 4: Rise of the Silver Surfer',
  216: 'Life of Pi',
  217: 'Ghost Rider',
  218: 'Jason Bourne',
  219: "Charlie's Angels: Full Throttle",
  220: 'Prometheus',
  221: 'Stuart Little 2',
  222: 'Elysium',
  223: 'The Chronicles of Riddick',
  224: 'RoboCop',
  225: 'Speed Racer',

In [215]:
pickle.dump(new_df.to_dict(),open('movies_dict.pkl','wb'))

In [218]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity



cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()
similarity = cosine_similarity(vectors)